# Generated by Django 5.2.8 on 2025-12-10 08:34

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado - como nuevo', 'Usado - como nuevo'), ('Usado - buen estado', 'Usado - buen estado'), ('Usado - aceptable', 'Usado - aceptable')], max_length=50)),
                ('access_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('qr_code_data', models.TextField(help_text='QR code data (deep link format)')),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('LOCKED', 'Locked (In Escrow)'), ('IN_TRANSIT', 'In Transit'), ('RELEASED', 'Released'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('REFUNDED', 'Refunded')], default='DRAFT', max_length=50, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contracts/%Y/%m/%d/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = main photo)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='transactions.contract')),
            ],
            options={
                'verbose_name': 'Contract Photo',
                'verbose_name_plural': 'Contract Photos',
                'db_table': 'contract_photos',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
